#!/usr/bin/env bash
# Produce a dated, clean snapshot of the repo for hackathon submission:
#   - writes BUILD.md with the date + git SHA
#   - creates dist/swarmops-<date>.zip from tracked files (git archive)
#   - optionally tags the commit hackathon-<date>
# Run from the repository root (or via `make snapshot`). Requires a committed tree.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

STAMP="$(date +%Y-%m-%d)"
STAMP_FILE="$(date +%Y%m%d-%H%M)"
SHA="$(git rev-parse --short HEAD 2>/dev/null || echo 'no-git')"

cat > BUILD.md <<EOF
# Build snapshot

- Date: ${STAMP}
- Commit: ${SHA}
- Event: Self-Evolving Agents Hackathon (tokens&)

Generated by \`make snapshot\`. This stamps the build for submission; the source of
truth is the git history at commit ${SHA}.
EOF
echo "Wrote BUILD.md (date ${STAMP}, commit ${SHA})."

mkdir -p dist
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  OUT="dist/swarmops-${STAMP_FILE}.zip"
  # Archive tracked files only (respects .gitignore) plus the fresh BUILD.md.
  git add BUILD.md 2>/dev/null || true
  git stash create >/dev/null 2>&1 || true
  git archive --format=zip -o "$OUT" HEAD
  echo "Wrote $OUT (tracked files at HEAD)."
  echo "Tip: commit BUILD.md and tag the submission:"
  echo "  git commit -am 'Snapshot ${STAMP}' && git tag hackathon-${STAMP} && git push --tags"
else
  echo "Not a git repo — BUILD.md written, skipping archive."
fi
